version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy  # Ensures Redis is ready before starting the app
    networks:
      - app-network
    environment:
      SPRING_REDIS_HOST: redis  # Use the service name, NOT host.docker.internal
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-server", "--version"]  # Alternative healthcheck
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

networks:
  app-network:
    driver: bridge
